### PR TITLE
Fix version regex and use lowercase symbols for versions

### LINKED ISSUE #2143: [Ruby] Examples are showing incorrect construction of client objects
It looks like the Ruby examples were recently changed from, e.g.:

```ruby
require "google/cloud/tasks/v2beta2"
cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new
#...
```

To

```ruby
require "google/cloud/tasks"
cloud_tasks_client = Google::Cloud::Tasks::V2beta2.new(version: :V2beta2)
#...
```

This is incorrect. It needs to be:

```ruby
require "google/cloud/tasks"
cloud_tasks_client = Google::Cloud::Tasks.new(version: :v2beta2)
#...
```

Note the TWO corrections:
* Need to call `new` on the service module, not the version module, if you want to pass a version argument.
* The version argument is misspelled; it should not be capitalized.

See https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2186 for an example.

### PR DESCRIPTION
**Pull request by jbolinger**
Fixes #2143 by updating the version regular expressions so it matches versions like "v1beta1" instead of only matching "v1". Also, update the version symbols used in the examples to be lower case.

### CODE REVIEW

File: src/main/java/com/google/api/codegen/util/CommonRenderingUtil.java [hunk 1]
```diff
@@ -112,4 +112,9 @@ public static String padding(int width) {
   public static int toInt(String value) {
     return Integer.valueOf(value);
   }
+
+  /** Returns the lowercase version of the given text */
+  public static String lowercase(String value) {
```
Comment (landrito) [inline src/main/java/com/google/api/codegen/util/CommonRenderingUtil.java]: Is this method needed?

Comment (jbolinger) [reply src/main/java/com/google/api/codegen/util/CommonRenderingUtil.java]: Is there a better way to lowercase a string in a snip file (like a built-in)?

I didn't want to add another property on the model because the capitalized version is used for other things and two properties for the version seems odd.

Comment (landrito) [reply src/main/java/com/google/api/codegen/util/CommonRenderingUtil.java]: `{@apiMethod.apiVersion.toLowerCase}`

Comment (jbolinger) [reply src/main/java/com/google/api/codegen/util/CommonRenderingUtil.java]: Done. Thanks for the pointer!

**Comment by dazuma** [comment]
@jbolinger I tried running artman 0.14.1 (image on dockerhub built the afternoon of 7/16) and this change doesn't seem to have made it in yet. How long does it usually take?

**Comment by jbolinger** [comment]
@dazuma it's typically an ad hoc process, but from the commit hash I think that change should have been included. It's possible I didn't fix it properly. Did either change show up (i.e. the lowercase symbol or the require path)? I'll see if I can run it myself between my meetings today.
